version: '3.9'

services:
  source-db:
    container_name: ${SOURCE_POSTGRES_HOST}
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'Asia/Tokyo'
    ports:
      - '${SOURCE_POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - source-db-data:/var/lib/postgresql/data
      - type: bind
        source: '${PWD}'
        target: /usr/share/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sandbox

  dest-db:
    container_name: ${DEST_POSTGRES_HOST}
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'Asia/Tokyo'
    ports:
      - '${DEST_POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - dest-db-data:/var/lib/postgresql/data
      - type: bind
        source: '${PWD}'
        target: /usr/share/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sandbox

volumes:
  source-db-data:
    name: source-db-data
    driver: local
  dest-db-data:
    name: dest-db-data
    driver: local

networks:
  sandbox:
    name: sandbox
